# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artboard', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('share', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='artboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_svg.Project'),
        ),
    ]
