# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0004_auto_20170118_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
    ]
