# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0006_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(max_length=100),
        ),
    ]
