# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0007_auto_20170118_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
