# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0008_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 1, 6, 31, 20, 96479)),
        ),
        migrations.AddField(
            model_name='project',
            name='density',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 1, 6, 31, 20, 96509)),
        ),
        migrations.AddField(
            model_name='project',
            name='screen',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
