# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0010_auto_20170201_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 6, 36, 34, 313638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 6, 36, 34, 313669, tzinfo=utc)),
        ),
    ]
