# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0012_auto_20170201_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='artboard',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
