# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0014_project_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_svg.ArtBoard')),
            ],
        ),
    ]
