# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0017_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='artboard',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artboard',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
