# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_svg', '0018_auto_20170213_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='edit',
        ),
    ]
